week:
  -
    portions: 28
    recipe-type: meal
    meal: lunch
    is_in_season: true
composite:
  -
    portions: 2
    recipe-type: meal
    meal: lunch
    tags: composite-vegetables
  -
    portions: 1
    recipe-type: meal
    meal: lunch
    tags: composite-carbs
  -
    portions: 1
    recipe-type: meal
    meal: lunch
    tags: composite-proteins
example:
  -
    portions: 24
    recipe-type: meal
    meal: lunch
    is_in_season: true
  -
    portions: 28
    recipe-type: meal
    meal: breakfast
  -
    portions: 16
    recipe-type: meal
    meal: snack
  -
    portions: 4
    recipe-type: meal
    meal: lunch
    tags: occasion
