example:
  -
    quantity: 6
    type: meal
    meal: lunch
    dish: main-course
    season: true
  -
    quantity: 7
    type: meal
    meal: breakfast
  -
    quantity: 4
    type: meal
    meal: snack
  -
    quantity: 1
    type: meal
    meal: lunch
    dish: main-course
    tags: cheat-meal