example:
  -
    quantity: 6
    recipe_type: meal
    meal: lunch
    dish: main-course
    is_in_season: true
  -
    quantity: 7
    recipe_type: meal
    meal: breakfast
  -
    quantity: 4
    recipe_type: meal
    meal: snack
  -
    quantity: 1
    recipe_type: meal
    meal: lunch
    dish: main-course
    tags: cheat-meal